---
title: "Setup"
output: 
  html_document:
    toc: false
    toc_float: false
---


We will be connecting to Jupyter Notebook Servers hosted on Pawsey's Nimbus Cloud. 
Each server has been pre-configured with the data and code ready to run through these tutorials.
Everyone will be issued with a unique web address and password.

**Go to the address you are given and you are ready to go!**


<br>

If you are arriving here in the future or would like to set up the environment on your local machine instead, follow these instructions:


## 1. Download the data

Grab a copy from [here.](https://sydney-informatics-hub.github.io/geopython-pawsey/data.tar.gz)

Or clone the repo and get the notebooks and data from the ```_ipynb``` directory:

```
git clone https://github.com/Sydney-Informatics-Hub/geopython-pawsey
```

<br>

## 2. Get a Python client

We generally use and recommend Miniconda Python distribution: [https://docs.conda.io/en/latest/miniconda.html](https://docs.conda.io/en/latest/miniconda.html). But feel free to use whatever one works for you (and the course materials). We will be using Miniconda3-py39_4.11.0.

You can get this specific version here for:

* [Windows 64 bit Download](https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Windows-x86_64.exe)

* [Mac OSX Download](https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-MacOSX-x86_64.pkg)

* [Linux Download](https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Linux-x86_64.sh)

Follow the prompts (the default recommendations in the installer are generally fine.) 
Once installed, launch an "Anaconda Prompt" from the Start Menu / Applications Folder to begin your Python adventure. 


<br>


## 3. Setup your Python environment (install required packages and libraries)

Next we need to set up an environment with all the additional packages and libraries we will be using throughout the course.

```
conda install -c defaults -c conda-forge python=3.9 scikit-learn=0.23.2 seaborn=0.11.2 numpy=1.20.3 pandas=1.2.3 scipy=1.5.3 
pip install jupyterlab==3.3.3 pyshp==2.1.3 shapely==1.8.1 upsetplot==0.6.0
```

This should install other key libraries e.g. ```numpy, matplotlib, pandas``` as dependencies.


<br>

# DEVS: To setup the (relatively unsecure) Jupyter Notebook server on a Pawsey Nimbus Cloud instance

These are the instructions we used to provide the notebook instance as a weblink.

```
jupyter notebook --generate-config
```

Use Python to set and generate a password hashed password
```
python -c "from notebook.auth import passwd; print(passwd())"
```

Edit the config file that was created
```
vi ~/.jupyter/jupyter_notebook_config.py
```

Set these lines
```
c.NotebookApp.allow_password_change = True
c.NotebookApp.ip = '*'
c.NotebookApp.password = 'PASSWORDHERE'
```

Launch the notebook server
```
cd /home/ubuntu/geopython-pawsey/_ipynb
nohup jupyter notebook > ~/notebook.log &
```

If you later want to kill the server, log back in, determine the id of the process and kill it.
```
ps -ef | grep python
kill -9 <id>
```


